"""Exports - annotated .h5ad, a re-runnable script, and a self-contained HTML report.

These are the "outlasts the week" deliverables: the scientist hands the `.h5ad` to a
bioinformatician, shares the HTML with the PI, and re-runs the exact analysis from the
script (assembled from the session action log).
"""

from __future__ import annotations

import base64
import io as _io
from pathlib import Path

_SCRIPT_HEADER = '''# Auto-generated by SpatialScribe - reproduces this section's analysis end to end.
# Requires the SpatialScribe environment (`pixi install -e main`).
from spatialscribe.analysis import io, capabilities as cap

ctx = cap.RunContext(tissue="{tissue}")
'''

_LOADER_PLACEHOLDER = (
    '\n# 1) Point this at your section (a Xenium/CosMx/MERSCOPE output folder or a .h5ad):\n'
    'adata = io.load("PATH/TO/YOUR/SECTION").adata\n\n# 2) Reproduce the analysis:\n'
)


def _loader(source_path: str | None) -> str:
    """The section-loading block: the real path when known (directly runnable), else a placeholder."""
    if source_path:
        return (f'\n# 1) Your section:\nadata = io.load({source_path!r}).adata\n\n'
                '# 2) Reproduce the analysis:\n')
    return _LOADER_PLACEHOLDER

# Control probes are kept through QC (so pct_control is measured on the real matrix), then dropped
# before clustering/annotation. Emitted right after compute_qc.
_CONTROL_DROP = (
    '# Controls were measured in QC above; drop them for clustering/annotation:\n'
    'if "control" in adata.var.columns:\n'
    '    adata = adata[:, ~adata.var["control"].to_numpy(dtype=bool)].copy()\n'
)

# The canonical SpatialScribe pipeline, in order, with the params the demo cache was built with
# and a predicate that says "this step's primary output is present in the current object". The
# re-runnable script emits every step whose output is present (so it reproduces the SHOWN state,
# not just whatever was clicked this session), overriding params from the session log when a step
# was run interactively.
_PIPELINE = [
    ("compute_qc",  {},                  lambda a: "total_counts" in a.obs),
    ("panel_check", {},                  lambda a: "panel_check" in a.uns),
    ("cluster",     {"resolution": 1.0}, lambda a: "leiden" in a.obs),
    ("annotate",    {},                  lambda a: "cell_type" in a.obs),
    ("niches",      {},                  lambda a: "niche" in a.obs),
]


def _h5ad_safe(value):
    """Recursively replace '/' in dict keys - h5py forbids slashes in group keys, so a nested uns
    dict keyed by cell types like 'Epithelial/Tumor' or 'Stromal/CAF' (e.g. panel_check.coverage)
    otherwise makes write_h5ad raise. Values and non-dict containers pass through unchanged."""
    if isinstance(value, dict):
        return {str(k).replace("/", "_"): _h5ad_safe(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_h5ad_safe(v) for v in value]
    if isinstance(value, tuple):
        return tuple(_h5ad_safe(v) for v in value)
    return value


def export_h5ad(adata, path: str | Path) -> Path:
    """Write the annotated AnnData (cell types, states, QC, panel_check in .uns).

    Sanitizes only ``uns`` keys (cheap - no cell-matrix copy) so a section that has run Panel check
    still exports; the live object's ``uns`` is restored afterwards so the running session is intact.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    orig_uns = adata.uns
    try:
        adata.uns = _h5ad_safe(dict(orig_uns))
        adata.write_h5ad(path)
    finally:
        adata.uns = orig_uns
    return path


def _render_entry(entry: dict) -> str:
    """Render one action-log record to a code line.

    Structured records ``{name, params}`` (the current provenance format, emitted by both
    the wizard and the copilot) render to a ``cap.run(...)`` call assembled from the
    registry, so the script never drifts from the real function signature. Legacy
    ``{label, code}`` records fall back to their stored snippet.
    """
    if "name" in entry and "code" not in entry:
        import json
        name = entry["name"]
        # Normalize params to JSON-safe primitives so a numpy/other scalar degrades to a plain
        # literal (the generated script imports neither numpy nor anndata).
        params = json.loads(json.dumps(entry.get("params", {}), default=str))
        return f"# --- {name} ---\ncap.run(adata, {name!r}, {params!r}, ctx)\n"
    code = entry.get("code", "")
    if code:
        return f"# --- {entry.get('label', '')} ---\n{code}\n"
    return ""


def build_runnable_script(action_log: list[dict] | None, adata=None, tissue: str = "melanoma",
                          source_path: str | None = None) -> str:
    """A complete, runnable reproduction script: header + section loader + the pipeline.

    Emits the canonical SpatialScribe pipeline (:data:`_PIPELINE`) in order. A step is included
    when its primary output is present on ``adata`` (so the script reproduces the SHOWN state,
    not merely the steps clicked this session) or when it appears in the session log; params come
    from the log when the step was run interactively, else the canonical demo params. Meaningful
    copilot-run analyses outside the standard pipeline (those that produce state) are appended in
    log order. With ``adata=None`` every canonical step is emitted (no state to introspect).
    """
    logged: dict[str, dict] = {}
    for entry in (action_log or []):
        if isinstance(entry, dict) and entry.get("name"):
            logged[entry["name"]] = entry.get("params") or {}

    parts = [_SCRIPT_HEADER.format(tissue=tissue), _loader(source_path)]
    emitted: list[str] = []
    for name, default_params, present in _PIPELINE:
        include = (name in logged) or (present(adata) if adata is not None else True)
        if not include:
            continue
        parts.append(_render_entry({"name": name, "params": logged.get(name, default_params)}))
        if name == "compute_qc":
            parts.append(_CONTROL_DROP)
        emitted.append(name)

    # Copilot-run analyses beyond the standard pipeline that actually produce state (e.g. subcluster,
    # malignant_score, discover_programs), plus any LEGACY {label, code} records - appended once, in
    # log order. Legacy snippets are emitted verbatim (provenance) so a hand-logged step is never lost.
    try:
        from . import capabilities as _cap
        pipeline_names = {p[0] for p in _PIPELINE}
        for entry in (action_log or []):
            if not isinstance(entry, dict):
                continue
            name = entry.get("name")
            if name:
                if name in emitted or name in pipeline_names:
                    continue
                cap = _cap.REGISTRY.get(name)
                if cap is not None and cap.produces:
                    parts.append(_render_entry({"name": name, "params": entry.get("params") or {}}))
                    emitted.append(name)
            elif entry.get("code"):
                parts.append(_render_entry(entry))          # legacy {label, code} snippet
                emitted.append(entry.get("label") or "code")
    except Exception:
        pass

    if not emitted:
        parts.append("# (no analysis steps have run on this section yet)\n")
    return "\n".join(parts)


def export_script(action_log: list[dict], path: str | Path, tissue: str = "melanoma", adata=None,
                  source_path: str | None = None) -> Path:
    """Write the runnable reproduction script (see :func:`build_runnable_script`) to ``path``.

    ``source_path`` (the loaded section's path) is threaded into the script's loader so the emitted
    ``rerun.py`` re-loads the REAL section rather than a ``PATH/TO/YOUR/SECTION`` placeholder the
    user has to edit before it runs."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_runnable_script(action_log, adata=adata, tissue=tissue, source_path=source_path))
    return path


def fig_to_base64(fig, dpi: int = 150) -> str:
    """Render a figure to an inline base64 ``<img>`` src (self-contained HTML).

    Handles a matplotlib ``Figure`` (``savefig``) and, when kaleido is installed, a Plotly figure
    (``to_image``). Returns an empty string if the figure cannot be rasterized (e.g. a Plotly figure
    with no kaleido), so a report never crashes on one un-exportable panel. ``dpi`` applies to the
    matplotlib path (Plotly has no dpi; it is exported at scale 2).
    """
    if hasattr(fig, "savefig"):                                   # matplotlib
        buf = _io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight")
        buf.seek(0)
        return "data:image/png;base64," + base64.b64encode(buf.read()).decode()
    try:                                                          # Plotly (needs kaleido)
        png = fig.to_image(format="png", scale=2)
        return "data:image/png;base64," + base64.b64encode(png).decode()
    except Exception:
        return ""


def save_figure_png(fig, path: str | Path, dpi: int = 300) -> Path | None:
    """Write a single 300-DPI PNG for a matplotlib figure (a publication-grade deliverable).

    Returns the path, or ``None`` for a non-matplotlib figure with no kaleido (never raises)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if hasattr(fig, "savefig"):
        fig.savefig(path, format="png", dpi=dpi, bbox_inches="tight")
        return path
    try:
        fig.write_image(str(path), scale=3)                      # ~300 DPI for a Plotly fig w/ kaleido
        return path
    except Exception:
        return None


_REPORT_CSS = (
    "body{font-family:system-ui,sans-serif;max-width:1000px;margin:2rem auto;padding:0 1rem;"
    "color:#1a1a1a}h1{border-bottom:2px solid #6b46c1}h2{margin-top:2rem;color:#6b46c1}"
    "img{max-width:100%}table{border-collapse:collapse;margin:.5rem 0}"
    "td,th{border:1px solid #ddd;padding:4px 8px;text-align:left}"
    "pre{background:#f6f6fa;border:1px solid #e2e2ee;border-radius:6px;padding:10px;overflow:auto;font-size:12px}"
    ".muted{color:#666;font-size:13px}"
)


def render_report(title: str, sections: list[tuple[str, str]], path: str | Path) -> Path:
    """Write a self-contained HTML report from ``(heading, html_fragment)`` sections."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(f"<h2>{h}</h2>\n{frag}" for h, frag in sections)
    html = (
        f"<!doctype html><html><head><meta charset='utf-8'><title>{title}</title>"
        f"<style>{_REPORT_CSS}</style></head><body><h1>{title}</h1>{body}</body></html>"
    )
    path.write_text(html)
    return path


# --------------------------------------------------------------------------- #
# Report assembly - a shareable HTML summary of the run + 300-DPI figure PNGs.
# The figures are matplotlib (self-contained, no kaleido needed - the interactive
# Plotly canvas is the app's job; the report is the "hand it to your PI" artifact).
# --------------------------------------------------------------------------- #
def _cat_palette(n: int):
    import matplotlib.cm as cm
    base = list(cm.tab20.colors) + list(cm.tab20b.colors) + list(cm.tab20c.colors)
    return [base[i % len(base)] for i in range(max(1, n))]


def composition_table(adata, key: str | None = None):
    """``(counts_per_cell_type, abstained_fraction)`` for the section.

    Abstained cells are EXCLUDED from the counts (they are not a cell type) while their share is
    returned so the caller can state it. Dropping them silently would change the denominator behind
    the reader's back; drawing them as bars would assert a lineage that was explicitly not called.

    ``abstained_fraction`` counts every cell whose FINAL label is not a lineage, which is a superset
    of ``apply_confidence``'s ``pct_abstain`` (the confidence-verdict FAIL rate): it also covers the
    honest ``Novel / unknown`` calls and the leiden-NaN ``Unassigned`` cells, which are not lineages
    even when their confidence is fine. Measured on a real Prime 5K section: 15.5% here vs 10.8%
    pct_abstain. The two numbers answer different questions and are both correct.
    """
    from . import annotate as _an

    key = key or _an.annotation_key(adata)
    lab = adata.obs[key].astype(str)
    typed = ~_an.abstention_mask(lab.to_numpy())
    abstained_frac = float((~typed).mean()) if len(lab) else 0.0
    return lab[typed].value_counts(), abstained_frac


def _fig_composition(adata, key: str = "cell_type"):
    """Horizontal bar chart of cell-type composition (matplotlib). Returns a Figure or None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    if key not in adata.obs:
        return None
    counts, abstained = composition_table(adata, key)
    if counts.empty:
        return None
    vc = counts.head(20)[::-1]
    fig, ax = plt.subplots(figsize=(6.5, max(2.2, 0.32 * len(vc))))
    ax.barh(range(len(vc)), vc.to_numpy(), color=_cat_palette(len(vc)))
    ax.set_yticks(range(len(vc)))
    ax.set_yticklabels([str(i) for i in vc.index], fontsize=8)
    ax.set_xlabel("cells")
    ax.set_title(f"Composition ({key}, {int(vc.sum()):,} typed cells; "
                 f"{abstained:.1%} abstained, excluded)")
    fig.tight_layout()
    return fig


def _fig_spatial(adata, key: str = "cell_type", max_points: int = 60000):
    """Spatial scatter colored by a categorical obs field (matplotlib). Returns a Figure or None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    if "spatial" not in adata.obsm or key not in adata.obs:
        return None
    from . import annotate as _an

    xy = np.asarray(adata.obsm["spatial"], dtype=float)
    # Abstained cells stay on the map (they occupy real tissue) but collapse into ONE grey category:
    # five abstention pseudo-labels became five coloured legend entries that read as lineages.
    lab = _an.collapse_abstention(adata.obs[key]).astype(str).to_numpy()
    n = xy.shape[0]
    if n > max_points:                                        # downsample dense sections for the PNG
        idx = np.random.default_rng(0).choice(n, size=max_points, replace=False)
        xy, lab = xy[idx], lab[idx]
    typed_cats = sorted(c for c in set(lab) if c != _an.NOT_ASSIGNED)
    colors = dict(zip(typed_cats, _cat_palette(len(typed_cats))))
    cats = typed_cats
    if _an.NOT_ASSIGNED in set(lab):                          # drawn first, under the typed cells
        colors[_an.NOT_ASSIGNED] = (0.78, 0.78, 0.78)
        cats = [_an.NOT_ASSIGNED, *typed_cats]
    fig, ax = plt.subplots(figsize=(7, 6.4))
    for c in cats:
        m = lab == c
        ax.scatter(xy[m, 0], xy[m, 1], s=2, c=[colors[c]], label=c, linewidths=0, rasterized=True)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.axis("off")
    ax.set_title(f"Spatial map ({key})")
    if len(cats) <= 24:
        ax.legend(markerscale=3, fontsize=6, loc="center left", bbox_to_anchor=(1, 0.5), frameon=False)
    fig.tight_layout()
    return fig


def _table_html(rows: list[tuple], headers: tuple[str, ...] | None = None) -> str:
    """Small HTML table from a list of tuples."""
    def esc(v):
        return str(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    head = f"<tr>{''.join(f'<th>{esc(h)}</th>' for h in headers)}</tr>" if headers else ""
    body = "".join("<tr>" + "".join(f"<td>{esc(c)}</td>" for c in r) + "</tr>" for r in rows)
    return f"<table>{head}{body}</table>"


def report_figures(adata) -> list[tuple[str, object]]:
    """The matplotlib figures for the report/PNG deliverables: ``(name, figure)`` pairs (skips None).

    Groups on ``annotate.annotation_key`` - the SAME column the computed statistics (composition,
    niches, neighborhood enrichment) group on. They disagreed once, so a delivered figure's
    percentages had a different denominator from the z-scores printed beside them.
    """
    from . import annotate as _an

    key = _an.annotation_key(adata)
    key = key if key in adata.obs else "leiden"
    figs = [("composition", _fig_composition(adata, key)),
            ("marker_dotplot", fig_marker_dotplot(adata, key)),
            ("spatial_celltypes", _fig_spatial(adata, key))]
    return [(n, f) for n, f in figs if f is not None]


# --------------------------------------------------------------------------- #
# Extra grounded sections - each guards on its own field(s) and returns an HTML
# fragment or None; every body is try/except-wrapped so one bad field never sinks
# the whole report. All read fields the pipeline already persists (no recompute
# that mutates the object). Heavy imports stay inside the functions.
# --------------------------------------------------------------------------- #
def _pct(mask) -> str:
    import numpy as np
    m = np.asarray(mask, dtype=bool)
    return f"{100 * m.mean():.0f}%" if m.size else "0%"


def _section_cell_states(adata) -> str | None:
    try:
        if "cell_state" not in adata.obs:
            return None
        vc = adata.obs["cell_state"].astype(str).value_counts()
        n = max(1, int(adata.n_obs))
        rows = [((s if s.lower() not in ("none", "nan") else "no dominant program"),
                 int(c), f"{100 * c / n:.0f}%") for s, c in vc.items()]
        html = _table_html(rows, headers=("State", "Cells", "% of cells"))
        cols = adata.uns.get("state_columns")
        if isinstance(cols, dict) and cols:
            html += (f"<p class='muted'>Programs scored: {', '.join(map(str, cols))}.</p>")
        return html
    except Exception:
        return None


def _section_niches(adata) -> str | None:
    try:
        if "niche" not in adata.obs:
            return None
        vc = adata.obs["niche"].astype(str).value_counts()
        n = max(1, int(adata.n_obs))
        rows = [(str(k), int(c), f"{100 * c / n:.0f}%") for k, c in vc.items()]
        return _table_html(rows, headers=("Niche", "Cells", "% of cells"))
    except Exception:
        return None


def _section_programs(adata) -> str | None:
    try:
        if not ("program" in adata.obs and "program_loadings" in adata.varm
                and "program_scores" in adata.obsm):
            return None
        import numpy as np
        from . import programs as _p
        load = np.asarray(adata.varm["program_loadings"])
        sc = np.asarray(adata.obsm["program_scores"])
        var = np.asarray(adata.var_names)
        dom = np.asarray(adata.obsm["programs"]).argmax(1) if "programs" in adata.obsm else None
        rows = []
        for k in range(load.shape[1]):
            top = ", ".join(str(g) for g in var[np.argsort(-load[:, k])[:6]])
            in_mask = (dom == k) if dom is not None else np.zeros(sc.shape[0], dtype=bool)
            pin = f"{sc[in_mask, k].mean():.2f}" if in_mask.any() else "n/a"
            pout = f"{sc[~in_mask, k].mean():.2f}" if (~in_mask).any() else "n/a"
            spec = _p._auroc(sc[:, k], in_mask)
            rows.append((f"Program {k}", int(in_mask.sum()), top, pin, pout,
                         f"{spec:.3g}" if spec == spec else "n/a"))   # spec==spec drops NaN
        return _table_html(rows, headers=("Program", "Cells", "Top genes", "signature (own)",
                                          "signature (rest)", "specificity (AUROC)"))
    except Exception:
        return None


def _section_malignant(adata) -> str | None:
    try:
        if "malignant_score" not in adata.obs:
            return None
        import numpy as np
        rows = [("Marker score > 0.6", _pct(np.asarray(adata.obs["malignant_score"], dtype=float) > 0.6))]
        if "is_malignant" in adata.obs:
            rows.append(("InSituCNV malignant", _pct(adata.obs["is_malignant"].to_numpy(dtype=bool))))
            if "cnv_score" in adata.obs:
                rows.append(("Median CNV score", f"{np.nanmedian(np.asarray(adata.obs['cnv_score'], dtype=float)):.3g}"))
        if "cancerfinder_malignant" in adata.obs:
            rows.append(("Cancer-Finder malignant", _pct(adata.obs["cancerfinder_malignant"].to_numpy(dtype=bool))))
        if "is_malignant" in adata.obs and "cancerfinder_malignant" in adata.obs:
            cfp = np.asarray(adata.obs.get("cancerfinder_prob", np.full(adata.n_obs, np.nan)), dtype=float)
            cnvs = np.asarray(adata.obs.get("cnv_score", np.full(adata.n_obs, np.nan)), dtype=float)
            m = ~np.isnan(cfp) & ~np.isnan(cnvs)
            if m.any():
                conc = (adata.obs["cancerfinder_malignant"].to_numpy(dtype=bool)[m]
                        == adata.obs["is_malignant"].to_numpy(dtype=bool)[m]).mean()
                rows.append(("Learned-caller concordance", f"{100 * conc:.0f}% (over {int(m.sum()):,} cells)"))
        return _table_html(rows, headers=("Caller", "Value"))
    except Exception:
        return None


def _section_rejection(adata) -> str | None:
    try:
        if "rejection_reason" not in adata.obs:
            return None
        from . import rejection as _rej
        df = _rej.rejection_breakdown(adata)
        if df is None or df.empty:
            return None
        rows = [(r["label"], int(r["n_cells"]), f"{r['pct_of_untyped']}%", r["description"])
                for _, r in df.iterrows()]
        return _table_html(rows, headers=("Reason", "Cells", "% of untyped", "Description"))
    except Exception:
        return None


def _section_qc_flags(adata) -> str | None:
    try:
        import numpy as np
        rows = []
        if "seg_area_flag" in adata.obs:
            rows.append(("Flagged segmentation", _pct(adata.obs["seg_area_flag"].astype(str).to_numpy() != "ok")))
        if "nucleus_present" in adata.obs:
            rows.append(("No nucleus detected", _pct(~adata.obs["nucleus_present"].to_numpy(dtype=bool))))
        if "vsi_confident" in adata.obs:
            rows.append(("Low VSI confidence", _pct(~adata.obs["vsi_confident"].to_numpy(dtype=bool))))
        if "crisp_impure" in adata.obs:
            rows.append(("Impure (CRISP)", _pct(adata.obs["crisp_impure"].to_numpy(dtype=bool))))
        if "spatial_coherence" in adata.obs:
            rows.append(("Median spatial coherence",
                         f"{np.nanmedian(np.asarray(adata.obs['spatial_coherence'], dtype=float)):.3g}"))
        return _table_html(rows, headers=("QC layer", "Value")) if rows else None
    except Exception:
        return None


def _section_annotation_quality(adata) -> str | None:
    """The section AQI + its A/C/M/G components, from ``uns['annotation_quality']`` (stamped by the
    pipeline's qc_funnel stage). The AQI is a 0-1 quality INDEX (monotone in quality, NOT P(correct));
    its purity term is trustworthy only when a reference grounds the markers, so an index_only regime
    (no >=3-method ensemble) carries the honest caveat. Returns an HTML fragment or None."""
    try:
        aq = adata.uns.get("annotation_quality")
        if not isinstance(aq, dict):
            return None
        aqi = aq.get("aqi") if isinstance(aq.get("aqi"), dict) else None
        if not aqi or aqi.get("aqi") is None:
            return None
        comp = aqi.get("components") or {}
        rows = [("AQI (0-1 section quality index, not P(correct))", f"{float(aqi['aqi']):.2f}")]
        for k, label in (("A", "Panel/depth adequacy (ceiling)"), ("C", "Contamination / purity"),
                         ("M", "Marker fidelity"), ("G", "Cross-method agreement")):
            v = comp.get(k)
            if v is not None:
                rows.append((label, f"{float(v):.2f}"))
        if aqi.get("argmin"):
            rows.append(("Limiting term", str(aqi["argmin"])))
        # Honesty note: without a >=3-method ensemble the index cannot see a coherent whole-cluster
        # mislabel (it scores only the labels present). Surface it, matching the app's AQI card.
        regime = aqi.get("regime") or (aqi.get("abstention") or {}).get("regime")
        if regime == "index_only" or comp.get("G") is None:
            rows.append(("Caveat", "no &ge;3-method ensemble voted - the index cannot see a coherent "
                                   "whole-cluster mislabel; run the reference annotators to confirm"))
        return _table_html(rows)
    except Exception:
        return None


def _section_panel_warnings(adata) -> str | None:
    try:
        pc = adata.uns.get("panel_check")
        if not isinstance(pc, dict):
            return None
        from . import rejection as _rej
        warns = _rej.panel_resolvability_warnings(adata, pc)
        if not warns:
            return None
        rows = [(w.get("cell_type", "?"), w.get("status", ""), int(w.get("n_cells", 0) or 0),
                 w.get("message", "")) for w in warns]
        return _table_html(rows, headers=("Cell type", "Status", "Cells", "Warning"))
    except Exception:
        return None


def render_analysis_report(adata, action_log: list[dict] | None = None, tissue: str = "melanoma",
                           path: str | Path = "report.html", source_path: str | None = None) -> Path:
    """Assemble a self-contained shareable HTML report of the whole run.

    Pulls the section summary, QC medians, panel-check verdict, annotatability and
    reference-match blocks from ``adata`` (whatever has been computed), inlines matplotlib figures
    (composition + spatial map) as base64 PNGs, and appends the re-runnable script. Every block is
    optional - the report shows what ran and silently omits what did not. Self-contained (no kaleido,
    no external assets)."""
    sections: list[tuple[str, str]] = []

    # 1) Section overview
    plat = adata.uns.get("platform", "?")
    npan = adata.uns.get("n_panel_genes", adata.n_vars)
    ov = [("Cells", f"{adata.n_obs:,}"), ("Genes (panel)", f"{npan:,}"),
          ("Platform", plat), ("Tissue context", tissue)]
    if "cell_type" in adata.obs:
        ov.append(("Cell types", str(adata.obs["cell_type"].astype(str).nunique())))
    sections.append(("Section", _table_html(ov)))

    # 1b) Pipeline stages - disclose which optional arms ran vs skipped/failed, so a marker-only run
    # is never read as one where SPLIT / malignant / self-heal actually fired (honest by disclosure,
    # not by omission). Populated by pipeline.run_pipeline; absent for an interactive ad-hoc session.
    pl = adata.uns.get("pipeline")
    if isinstance(pl, dict) and isinstance(pl.get("stages"), list) and pl["stages"]:
        srows = []
        for stg in pl["stages"]:
            kind, _, why = str(stg.get("status", "")).partition(":")
            label = {"ok": "ran", "skipped": "skipped", "failed": "FAILED"}.get(kind, kind or "?")
            srows.append((stg.get("name", "?"), label + (f" - {why}" if why else "")))
        sections.append(("Pipeline stages", _table_html(srows, headers=("Stage", "Status"))))

    # 2) QC medians
    try:
        from . import qc as _qc
        if "total_counts" in adata.obs:
            s = _qc.qc_summary(adata)
            sections.append(("Quality control", _table_html(
                [(k, (f"{v:.3g}" if isinstance(v, float) else v)) for k, v in s.items()])))
    except Exception:
        pass

    # 3) Panel check
    pc = adata.uns.get("panel_check")
    if isinstance(pc, dict) and isinstance(pc.get("coverage"), dict):
        cov = pc["coverage"]
        greens = [ct for ct, d in cov.items() if isinstance(d, dict) and d.get("status") == "green"]
        reds = [ct for ct, d in cov.items() if isinstance(d, dict) and d.get("status") == "red"]
        sections.append(("Panel adequacy", _table_html(
            [("Resolvable", ", ".join(greens) or "none"),
             ("Cannot resolve", ", ".join(reds) or "none")])))
        frag = _section_panel_warnings(adata)
        if frag:
            sections.append(("Panel resolvability warnings", frag))

    # 4) Annotatability / confidence
    if "annotation_verdict" in adata.obs:
        v = adata.obs["annotation_verdict"].astype(str)
        rows = [("PASS", f"{(v == 'PASS').mean():.0%}"), ("WARN", f"{(v == 'WARN').mean():.0%}"),
                ("Abstained", f"{(v == 'FAIL').mean():.0%}")]
        # Say what the abstention RESTS on, so a reader does not over-trust the greying. Measured:
        # the confidence heuristic barely ranks correct cells (within-lineage AUC ~0.54); cross-method
        # agreement does (~0.77). apply_confidence writes uns['abstention_basis'] with that call.
        ab = adata.uns.get("abstention_basis")
        if isinstance(ab, dict):
            rows.append(("Abstention basis",
                         "cross-method ensemble (reliable)" if ab.get("trustworthy")
                         else "confidence heuristic only (advisory - run the reference ensemble to make it reliable)"))
        sections.append(("Annotation confidence", _table_html(rows)))

    # 6) Reference match
    rm = adata.uns.get("reference_match")
    if isinstance(rm, dict) and rm.get("global"):
        g = rm["global"]
        sections.append(("Reference &harr; panel match", _table_html(
            [("Panel-gene overlap", f"{g.get('gene_overlap_frac', 0):.0%}"),
             ("Mean per-type F1", g.get("mean_f1")), ("Verdict", g.get("verdict"))])))

    # 6b) Extra grounded sections - each guarded, appended only when its field(s) are present.
    for heading, builder in (("Annotation quality (AQI)", _section_annotation_quality),
                             ("QC funnel flags", _section_qc_flags),
                             ("Cell states", _section_cell_states),
                             ("Spatial niches", _section_niches),
                             ("De-novo programs", _section_programs),
                             ("Malignant calling", _section_malignant),
                             ("Untyped-cell reasons", _section_rejection)):
        frag = builder(adata)
        if frag:
            sections.append((heading, frag))

    # 7) Figures (inline 150-DPI base64 for a light HTML)
    for name, fig in report_figures(adata):
        src = fig_to_base64(fig, dpi=150)
        if src:
            sections.append((name.replace("_", " ").title(), f'<img src="{src}" alt="{name}">'))
        import matplotlib.pyplot as _plt
        _plt.close(fig)

    # 8) Re-runnable script
    script = build_runnable_script(action_log, adata=adata, tissue=tissue, source_path=source_path)
    esc = script.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    sections.append(("Re-runnable analysis", f"<pre>{esc}</pre>"))

    sections.append(("", "<p class='muted'>Generated by SpatialScribe. Self-contained; no server "
                     "needed - open in any browser.</p>"))
    return render_report(f"SpatialScribe report - {tissue}", sections, path)


def save_report_pngs(adata, outdir: str | Path, dpi: int = 300) -> list[Path]:
    """Write the report figures as standalone 300-DPI PNGs into ``outdir``. Returns written paths."""
    import matplotlib.pyplot as plt
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, fig in report_figures(adata):
        p = save_figure_png(fig, outdir / f"{name}.png", dpi=dpi)
        plt.close(fig)
        if p is not None:
            written.append(p)
    return written


# --------------------------------------------------------------------------- #
# On-brand dark report figures - matplotlib -> the HTML report's base64 <img>s.
# The interactive Plotly canvas is the app's job; these are the self-contained
# "hand it to your PI" figures (no kaleido, no plotly). Every builder guards on
# the obs column(s) it needs and returns a Figure or None, so a section that has
# only been loaded + QC'd omits the annotation figures instead of raising.
# Colours are the report brand tokens (docs/BRAND.md report surface): dark field
# #0b0c10, violet #a896f2, pass #46e39b, warn #f2b24c, fail #f7746e.
# --------------------------------------------------------------------------- #
_R_BG = "#0b0c10"
_R_PANEL = "#14161c"
_R_INK = "#e7e9ee"
_R_MUTED = "#8892a6"
_R_LINE = "#262a34"
_R_VIOLET = "#a896f2"
_R_PASS = "#46e39b"
_R_WARN = "#f2b24c"
_R_FAIL = "#f7746e"


def _r_style(fig, *axes):
    """Apply the dark report theme to a figure and its axes in place (spines, ticks, labels)."""
    fig.patch.set_facecolor(_R_BG)
    for ax in axes:
        ax.set_facecolor(_R_BG)
        for s in ax.spines.values():
            s.set_color(_R_LINE)
        ax.tick_params(colors=_R_MUTED, labelsize=8, length=3)
        ax.xaxis.label.set_color(_R_MUTED)
        ax.yaxis.label.set_color(_R_MUTED)
        ax.title.set_color(_R_INK)


def fig_qc_histograms(adata):
    """Counts-per-cell (+ genes-per-cell) histograms on a log x-axis, with the panel-indexed count
    floor drawn as a vertical rule and the removed fraction annotated. Needs ``obs['total_counts']``;
    the genes panel is added only when ``obs['n_genes_by_counts']`` is present. Returns Figure|None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    from . import qc as _qc
    if "total_counts" not in adata.obs:
        return None
    counts = np.asarray(adata.obs["total_counts"], dtype=float)
    genes = (np.asarray(adata.obs["n_genes_by_counts"], dtype=float)
             if "n_genes_by_counts" in adata.obs else None)
    floor = float(_qc.suggest_count_floor(adata).get("floor", 0.0))
    removed = float(np.mean(counts < floor)) if floor > 0 and counts.size else 0.0

    ncol = 2 if genes is not None else 1
    fig, axes = plt.subplots(1, ncol, figsize=(4.6 * ncol, 3.2))
    axes = np.atleast_1d(axes)
    _r_style(fig, *axes)

    def _loghist(ax, vals, colour, xlabel, rule=None, rule_note=None):
        pos = vals[vals > 0]
        if pos.size == 0:
            ax.text(0.5, 0.5, "no positive values", ha="center", va="center",
                    color=_R_MUTED, transform=ax.transAxes)
            return
        bins = np.logspace(np.log10(pos.min()), np.log10(pos.max()), 44)
        ax.hist(pos, bins=bins, color=colour, alpha=0.85, edgecolor=_R_BG, linewidth=0.3)
        ax.set_xscale("log")
        ax.set_xlabel(xlabel)
        ax.set_ylabel("cells")
        if rule and rule > 0:
            ax.axvline(rule, color=_R_FAIL, linestyle="--", linewidth=1.4)
            if rule_note:
                ax.text(0.97, 0.94, rule_note, transform=ax.transAxes, ha="right", va="top",
                        color=_R_FAIL, fontsize=8.5)

    _loghist(axes[0], counts, _R_VIOLET, "transcripts / cell (log)", floor,
             f"count floor {floor:g}\n{removed * 100:.1f}% below")
    axes[0].set_title("counts per cell", fontsize=10, loc="left")
    if genes is not None:
        _loghist(axes[1], genes, "#6c8cff", "genes / cell (log)")
        axes[1].set_title("genes per cell", fontsize=10, loc="left")
    fig.tight_layout()
    return fig


def fig_qc_funnel(adata):
    """Horizontal QC funnel: cells surviving each successive gate (cumulative AND of the gates whose
    obs column is present). Gates, in pipeline order: loaded -> segmentation OK -> above count floor
    -> pure (PMP/CRISP) -> confidently/tentatively labelled. Reads only persisted columns (never
    mutates, never recomputes a heavy layer). Returns Figure|None (None if nothing beyond 'loaded')."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    from . import qc as _qc
    n = int(adata.n_obs)
    if n == 0:
        return None
    keep = np.ones(n, dtype=bool)
    rows = [("loaded", n)]
    if "seg_area_flag" in adata.obs:
        keep &= adata.obs["seg_area_flag"].astype(str).to_numpy() == "ok"
        rows.append(("segmentation OK", int(keep.sum())))
    if "total_counts" in adata.obs:
        floor = float(_qc.suggest_count_floor(adata).get("floor", 0.0))
        keep &= np.asarray(adata.obs["total_counts"], dtype=float) >= floor
        rows.append(("above count floor", int(keep.sum())))
    if "crisp_impure" in adata.obs:
        keep &= ~adata.obs["crisp_impure"].to_numpy(dtype=bool)
        rows.append(("pure (PMP)", int(keep.sum())))
    if "annotation_verdict" in adata.obs:
        keep &= adata.obs["annotation_verdict"].astype(str).to_numpy() != "FAIL"
        rows.append(("confidently labelled", int(keep.sum())))
    if len(rows) < 2:                                    # only 'loaded' is computable - nothing to show
        return None

    labels = [r[0] for r in rows]
    vals = [r[1] for r in rows]
    y = np.arange(len(rows))[::-1]                       # first gate on top
    fig, ax = plt.subplots(figsize=(7.6, 0.62 * len(rows) + 1.0))
    _r_style(fig, ax)
    ax.barh(y, [n] * len(rows), color=_R_PANEL, height=0.66)          # full-width reference track
    ax.barh(y, vals, color=_R_VIOLET, height=0.66)                    # survivors
    for yi, lab, v in zip(y, labels, vals):
        ax.text(n * 0.012, yi, lab, va="center", ha="left", color=_R_BG, fontsize=9, fontweight="bold")
        ax.text(n * 0.99, yi, f"{v:,}  ({100 * v / n:.0f}%)", va="center", ha="right",
                color=_R_INK, fontsize=8.5)
    ax.set_yticks([])
    ax.set_xlim(0, n)
    ax.set_xlabel("cells surviving (cumulative)")
    ax.spines["left"].set_visible(False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    return fig


def fig_composition_bar(adata, colour_map=None, key="cell_type", top=14):
    """A single 100%-stacked horizontal composition bar of the section's cell types (rank-ordered,
    the tail merged into 'other'). ``colour_map`` maps a label to an RGB float tuple so the segments
    match the spatial map's palette; unknown labels fall back to grey. Needs ``obs[key]``. Fig|None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    if key not in adata.obs:
        return None
    vc = adata.obs[key].astype(str).value_counts()
    total = int(vc.sum())
    if total == 0:
        return None
    head = vc.head(top)
    tail = int(vc.iloc[top:].sum())
    names = list(head.index) + (["other"] if tail > 0 else [])
    counts = list(head.to_numpy()) + ([tail] if tail > 0 else [])
    cmap = colour_map or {}

    def _col(name):
        c = cmap.get(name)
        return (tuple(c) if c is not None else (0.42, 0.45, 0.5))

    fig, ax = plt.subplots(figsize=(7.6, 1.9))
    _r_style(fig, ax)
    left = 0.0
    for name, c in zip(names, counts):
        frac = 100 * c / total
        ax.barh(0, frac, left=left, color=_col(name), height=0.62, edgecolor=_R_BG, linewidth=0.6)
        if frac >= 6:                                    # only label segments wide enough to read
            ax.text(left + frac / 2, 0, f"{name}\n{frac:.0f}%", va="center", ha="center",
                    color="#0b0c10", fontsize=7.6, fontweight="bold")
        left += frac
    ax.set_xlim(0, 100)
    ax.set_ylim(-0.5, 0.5)
    ax.set_yticks([])
    ax.set_xlabel("% of cells")
    for side in ("left", "top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    return fig


def fig_marker_dotplot(adata, key: str = "cell_type", n_types: int = 22, genes_per_type: int = 2):
    """Dot plot of the top DATA-DRIVEN marker genes per annotated cell type - the honest
    "do the labels express distinct genes?" check.

    Markers are the section's own DEGs (``rank_genes_groups``), NOT a curated dictionary, so it works
    for ANY label vocabulary - curated lineages OR a reference-transfer atlas (the fine MOCA embryo
    types osteoblast/myotube/... which no human-tissue marker dict anticipates). Dot SIZE = fraction
    of the type's cells expressing the gene; COLOUR = per-gene min-max-scaled mean expression across
    the shown types, so each column's brightest dot is the type it marks. Groups on the largest
    ``n_types`` real types (abstention labels dropped). Returns Figure|None.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    import scipy.sparse as sp
    from collections import Counter
    from . import annotate as _an
    if key not in adata.obs:
        return None
    labels_full = adata.obs[key].astype(str).to_numpy()
    typed = ~_an.abstention_mask(labels_full)
    if typed.sum() < 20:
        return None
    types = [t for t, _ in Counter(labels_full[typed]).most_common(n_types)]
    if len(types) < 2:
        return None
    # rank genes per type on a (subsampled) view restricted to the shown types - cheap on 466 genes.
    import scanpy as sc
    keep = typed & np.isin(labels_full, types)
    sub = adata[keep].copy()
    if sub.n_obs > 60000:
        idx = np.random.default_rng(0).choice(sub.n_obs, 60000, replace=False)
        sub = sub[np.sort(idx)].copy()
    sub.obs["_k"] = sub.obs[key].astype(str).astype("category")
    if sub.obs["_k"].nunique() < 2:
        return None
    try:
        sc.tl.rank_genes_groups(sub, "_k", method="t-test", n_genes=genes_per_type + 4)
    except Exception:
        return None
    names = sub.uns["rank_genes_groups"]["names"]
    genes: list[str] = []
    for t in types:                                          # keep the type order for a readable diagonal
        if t in names.dtype.names:
            for g in list(names[t])[:genes_per_type]:
                g = str(g)
                if g in sub.var_names and g not in genes:
                    genes.append(g)
    if len(genes) < 2:
        return None
    X = sub[:, genes].X
    X = X.toarray() if sp.issparse(X) else np.asarray(X)
    lab = sub.obs[key].astype(str).to_numpy()
    frac = np.zeros((len(types), len(genes)))
    mean = np.zeros_like(frac)
    for i, t in enumerate(types):
        m = lab == t
        if m.any():
            xt = X[m]
            frac[i] = (xt > 0).mean(0)
            mean[i] = xt.mean(0)
    rng = np.clip(mean.max(0, keepdims=True) - mean.min(0, keepdims=True), 1e-9, None)
    scaled = (mean - mean.min(0, keepdims=True)) / rng

    fig, ax = plt.subplots(figsize=(max(6.0, 0.34 * len(genes) + 2.4), max(3.6, 0.30 * len(types) + 1.2)))
    _r_style(fig, ax)
    yy, xx = np.mgrid[0:len(types), 0:len(genes)]
    sca = ax.scatter(xx.ravel(), yy.ravel(), s=(12 + 150 * frac).ravel(), c=scaled.ravel(),
                     cmap="magma", edgecolors="none", vmin=0, vmax=1)
    ax.set_xticks(range(len(genes)))
    ax.set_xticklabels(genes, rotation=90, fontsize=6, color=_R_INK)
    ax.set_yticks(range(len(types)))
    ax.set_yticklabels(types, fontsize=6.5, color=_R_INK)
    ax.set_xlim(-0.5, len(genes) - 0.5)
    ax.set_ylim(-0.5, len(types) - 0.5)
    ax.invert_yaxis()
    ax.set_title("Top marker genes per cell type (data-driven DEGs)", fontsize=9)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    cb = fig.colorbar(sca, ax=ax, fraction=0.022, pad=0.015)
    cb.set_label("scaled mean expr", color=_R_MUTED, fontsize=6.5)
    cb.ax.tick_params(colors=_R_MUTED, labelsize=6)
    fig.tight_layout()
    return fig


def fig_confidence_meter(adata):
    """The annotatability headline as a real stacked bar: confident / tentative / abstained
    (PASS / WARN / FAIL) with per-segment counts. Needs ``obs['annotation_verdict']``. Fig|None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    if "annotation_verdict" not in adata.obs:
        return None
    v = adata.obs["annotation_verdict"].astype(str).to_numpy()
    n = v.size
    if n == 0:
        return None
    segs = [("confident", int((v == "PASS").sum()), _R_PASS),
            ("tentative", int((v == "WARN").sum()), _R_WARN),
            ("abstained", int((v == "FAIL").sum()), _R_FAIL)]
    fig, ax = plt.subplots(figsize=(7.6, 1.35))
    _r_style(fig, ax)
    left = 0.0
    for name, c, colour in segs:
        if c == 0:
            continue
        frac = 100 * c / n
        ax.barh(0, frac, left=left, color=colour, height=0.6, edgecolor=_R_BG, linewidth=0.8)
        if frac >= 7:
            ax.text(left + frac / 2, 0, f"{name}\n{frac:.0f}%  ({c:,})", va="center", ha="center",
                    color="#0b0c10", fontsize=8, fontweight="bold")
        left += frac
    ax.set_xlim(0, 100)
    ax.set_ylim(-0.5, 0.5)
    ax.set_yticks([])
    ax.set_xticks([0, 25, 50, 75, 100])
    for side in ("left", "top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    return fig


def fig_confidence_ridges(adata, colour_map=None, conf_key="annotation_confidence",
                          label_key="cell_type", top=12):
    """Per-cell-type confidence distributions as horizontal violins (a small-multiple ridgeline):
    one row per cell type (top-N by count), the violin drawn over ``obs[conf_key]`` in [0,1], tinted
    to match the map palette. Needs ``obs[conf_key]`` and ``obs[label_key]``. Returns Figure|None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    if conf_key not in adata.obs or label_key not in adata.obs:
        return None
    conf = np.asarray(adata.obs[conf_key], dtype=float)
    lab = adata.obs[label_key].astype(str).to_numpy()
    order = [str(k) for k in adata.obs[label_key].astype(str).value_counts().head(top).index]
    data, names, colours = [], [], []
    cmap = colour_map or {}
    for name in order:
        vals = conf[(lab == name) & np.isfinite(conf)]
        if vals.size < 10:                               # too few cells for a meaningful violin
            continue
        data.append(vals)
        names.append(name)
        c = cmap.get(name)
        colours.append(tuple(c) if c is not None else (0.66, 0.59, 0.95))
    if not data:
        return None
    pos = np.arange(len(data))
    fig, ax = plt.subplots(figsize=(7.6, 0.42 * len(data) + 1.1))
    _r_style(fig, ax)
    parts = ax.violinplot(data, positions=pos, vert=False, widths=0.9,
                          showmeans=False, showextrema=False, showmedians=True)
    for body, colour in zip(parts["bodies"], colours):
        body.set_facecolor(colour)
        body.set_edgecolor(colour)
        body.set_alpha(0.72)
    if "cmedians" in parts:
        parts["cmedians"].set_color(_R_INK)
        parts["cmedians"].set_linewidth(1.0)
    ax.set_yticks(pos)
    ax.set_yticklabels(names, fontsize=8, color=_R_INK)
    ax.set_xlim(0, 1)
    ax.set_xlabel("per-cell annotation confidence")
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    return fig


def fig_rejection_bar(adata):
    """Horizontal bar chart of why cells were left unlabelled: the reason breakdown among abstained
    cells. Prefers the granular ``obs['rejection_reason']``, else the coarse ``obs['annotation_reason']``;
    restricted to FAIL cells when ``annotation_verdict`` is present. Returns Figure|None."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    col = "rejection_reason" if "rejection_reason" in adata.obs else (
        "annotation_reason" if "annotation_reason" in adata.obs else None)
    if col is None:
        return None
    reason = adata.obs[col].astype(str)
    if "annotation_verdict" in adata.obs:
        reason = reason[adata.obs["annotation_verdict"].astype(str).to_numpy() == "FAIL"]
    blank = {"", "nan", "none", "na", "<na>", "assigned", "confident", "pass"}
    reason = reason[~reason.str.lower().isin(blank)]
    vc = reason.value_counts().head(10)
    if vc.empty:
        return None
    labels = [str(i).replace("_", " ") for i in vc.index][::-1]
    vals = vc.to_numpy()[::-1]
    fig, ax = plt.subplots(figsize=(7.0, 0.44 * len(vals) + 1.0))
    _r_style(fig, ax)
    y = np.arange(len(vals))
    ax.barh(y, vals, color=_R_FAIL, alpha=0.85, height=0.62)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=8.5, color=_R_INK)
    for yi, v in zip(y, vals):
        ax.text(v, yi, f"  {int(v):,}", va="center", ha="left", color=_R_MUTED, fontsize=8)
    ax.set_xlabel("cells")
    ax.margins(x=0.12)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    return fig
