#!/usr/bin/env python
"""Regenerate the self-hosted (base64 woff2) app font files.

Why self-host: the Streamlit themes must render identically on any network. A Google Fonts
``@import`` silently falls back to a plain system font whenever the viewer's browser cannot reach
``fonts.googleapis.com`` (corporate proxy, VPN, offline, a CSP behind a reverse proxy), which makes
the UI look "generic / too simple". Embedding the woff2 as base64 removes that dependency - each
theme's ``inject()`` reads its file and injects it inline.

Two files, one per theme (all faces SIL Open Font License, so embedding is permitted):
  * app/fonts.css          - warm "field notebook" theme: Hanken Grotesk + Fira Code
  * app/fonts_stakent.css  - dark "control-desk" theme: Manrope + Space Grotesk + JetBrains Mono

Run from the project root:  python scripts/embed_fonts.py
Only the ``latin`` subset is embedded to keep each file small (~170-180 KB of font data).
"""
from __future__ import annotations

import base64
import re
import sys
import urllib.request
from pathlib import Path

_UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
       "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
_APP = Path(__file__).resolve().parents[1] / "src" / "spatialscribe" / "app"

# (output file, Google Fonts css2 family query, human label)
_TARGETS = [
    ("fonts.css",
     "family=Hanken+Grotesk:wght@400;600;800&family=Fira+Code:wght@400;600",
     "field-notebook theme (Hanken Grotesk + Fira Code)"),
    ("fonts_stakent.css",
     "family=Space+Grotesk:wght@600;700&family=Manrope:wght@400;600;700&family=JetBrains+Mono:wght@400;600",
     "control-desk theme (Space Grotesk + Manrope + JetBrains Mono)"),
]


def _fetch(url: str, binary: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": _UA})
    with urllib.request.urlopen(req, timeout=20) as resp:
        return resp.read() if binary else resp.read().decode()


def _embed(css: str) -> tuple[str, int]:
    faces, total = [], 0
    for subset, block in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
        if subset != "latin":  # latin subset only -> ~170 KB
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        woff2 = _fetch(m.group(1), binary=True)
        total += len(woff2)
        data_uri = f"url(data:font/woff2;base64,{base64.b64encode(woff2).decode()}) format('woff2')"
        faces.append(re.sub(r"src:\s*url\([^)]+\)\s*format\('woff2'\)", f"src:{data_uri}", block))
    return "\n".join(faces) + "\n", total


def main() -> int:
    for out_name, query, label in _TARGETS:
        css = _fetch(f"https://fonts.googleapis.com/css2?{query}&display=swap")
        body, total = _embed(css)
        header = (f"/* Self-hosted fonts for the {label} (base64 woff2, latin subset). "
                  "Generated by scripts/embed_fonts.py - do not hand-edit. OFL fonts. */\n")
        (_APP / out_name).write_text(header + body)
        print(f"wrote app/{out_name}: {total // 1024} KB font data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
